---
# Source: airflow/templates/scheduler/scheduler-serviceaccount.yaml
################################
## Airflow Scheduler ServiceAccount
#################################
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: airflow-scheduler
  namespace: "airflow"
  labels:
    tier: airflow
    component: scheduler
    release: airflow
    chart: "airflow-1.12.0"
    heritage: Helm