---
# Source: airflow/templates/workers/worker-serviceaccount.yaml
################################
## Airflow Worker ServiceAccount
#################################
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: airflow-worker
  namespace: "airflow"
  labels:
    tier: airflow
    component: worker
    release: airflow
    chart: "airflow-1.12.0"
    heritage: Helm