---
# Source: airflow/templates/webserver/webserver-serviceaccount.yaml
######################################
## Airflow Webserver ServiceAccount
######################################
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: airflow-webserver
  namespace: "airflow"
  labels:
    tier: airflow
    component: webserver
    release: airflow
    chart: "airflow-1.12.0"
    heritage: Helm