# Source: airflow/templates/jobs/create-user-job-serviceaccount.yaml
###########################################
## Airflow Create User Job ServiceAccount
###########################################
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: airflow-create-user-job
  namespace: "airflow-helm-project"
  labels:
    tier: airflow
    component: create-user-job
    release: airflow
    chart: "airflow-1.12.0"
    heritage: Helm